[helpers]

[default]
depends = []

[default.files]
clang-format = "~/.clang-format"
gitconfig = "~/.gitconfig"
xinitrc = "~/.xinitrc"
zshrc = "~/.zshrc"

[doom.files]
doom_init = "~/.doom.d/init.el"
doom_config = "~/.doom.d/config.el"
doom_packages = "~/.doom.d/packages.el"

[default.variables]
